// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module lz4CompressEngineRun_lzBooster_255_16384_64_Pipeline_lz_booster (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        match_loc_reg_load,
        nextMatchCh_loc_0,
        matchFlag_reg_load,
        match_len_reg_load,
        skip_len_reg_load,
        sub,
        local_mem_address0,
        local_mem_ce0,
        local_mem_q0,
        local_mem_address1,
        local_mem_ce1,
        local_mem_we1,
        local_mem_d1,
        bestMatchStream_dout,
        bestMatchStream_empty_n,
        bestMatchStream_read,
        bestMatchStream_num_data_valid,
        bestMatchStream_fifo_cap,
        boosterStream_din,
        boosterStream_full_n,
        boosterStream_write,
        boosterStream_num_data_valid,
        boosterStream_fifo_cap,
        new_match_loc_out,
        new_match_loc_out_ap_vld,
        p_out,
        p_out_ap_vld,
        new_matchFlag_1_0_0_07_out,
        new_matchFlag_1_0_0_07_out_ap_vld,
        new_match_len_out,
        new_match_len_out_ap_vld,
        p_out1,
        p_out1_ap_vld,
        outValue_out,
        outValue_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] match_loc_reg_load;
input  [7:0] nextMatchCh_loc_0;
input  [0:0] matchFlag_reg_load;
input  [31:0] match_len_reg_load;
input  [15:0] skip_len_reg_load;
input  [31:0] sub;
output  [13:0] local_mem_address0;
output   local_mem_ce0;
input  [7:0] local_mem_q0;
output  [13:0] local_mem_address1;
output   local_mem_ce1;
output   local_mem_we1;
output  [7:0] local_mem_d1;
input  [31:0] bestMatchStream_dout;
input   bestMatchStream_empty_n;
output   bestMatchStream_read;
input  [3:0] bestMatchStream_num_data_valid;
input  [3:0] bestMatchStream_fifo_cap;
output  [31:0] boosterStream_din;
input   boosterStream_full_n;
output   boosterStream_write;
input  [31:0] boosterStream_num_data_valid;
input  [31:0] boosterStream_fifo_cap;
output  [31:0] new_match_loc_out;
output   new_match_loc_out_ap_vld;
output  [7:0] p_out;
output   p_out_ap_vld;
output  [0:0] new_matchFlag_1_0_0_07_out;
output   new_matchFlag_1_0_0_07_out_ap_vld;
output  [31:0] new_match_len_out;
output   new_match_len_out_ap_vld;
output  [15:0] p_out1;
output   p_out1_ap_vld;
output  [31:0] outValue_out;
output   outValue_out_ap_vld;

reg ap_idle;
reg bestMatchStream_read;
reg boosterStream_write;
reg new_match_loc_out_ap_vld;
reg p_out_ap_vld;
reg new_matchFlag_1_0_0_07_out_ap_vld;
reg new_match_len_out_ap_vld;
reg p_out1_ap_vld;
reg outValue_out_ap_vld;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln624_reg_673;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    bestMatchStream_blk_n;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_grp1;
reg    ap_block_pp0_stage1_subdone_grp1_done_reg;
reg    ap_block_pp0_stage1_subdone_grp1;
reg    ap_block_pp0_stage1_subdone;
reg    boosterStream_blk_n;
wire    ap_block_pp0_stage1_grp2;
reg   [0:0] icmp_ln624_reg_673_pp0_iter1_reg;
reg   [0:0] skip_condition_reg_709;
reg   [0:0] match_condition_reg_713;
reg   [0:0] outFlag_reg_722;
reg    ap_block_pp0_stage1_subdone_grp2_done_reg;
reg    ap_block_pp0_stage1_subdone_grp2;
wire    ap_block_pp0_stage1_11001_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
wire    ap_block_pp0_stage1_subdone_grp0;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] i_4_reg_665;
wire   [0:0] icmp_ln624_fu_326_p2;
reg   [31:0] outValue_3_reg_677;
reg    ap_block_state2_pp0_stage1_iter0_grp1;
reg    ap_block_pp0_stage1_11001_grp1;
wire   [7:0] tCh_fu_332_p1;
reg   [7:0] tCh_reg_682;
reg   [7:0] tLen_reg_688;
reg   [15:0] tOffset_reg_694;
wire   [0:0] boostFlag_fu_362_p2;
reg   [0:0] boostFlag_reg_699;
reg   [31:0] outValue_1_reg_704;
wire   [0:0] skip_condition_fu_412_p2;
wire   [0:0] match_condition_fu_435_p2;
wire   [0:0] outFlag_fu_469_p2;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [7:0] ap_phi_reg_pp0_iter0_empty_41_reg_272;
reg   [7:0] ap_phi_reg_pp0_iter1_empty_41_reg_272;
wire    ap_block_pp0_stage2_11001;
wire   [63:0] zext_ln634_fu_376_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln680_fu_447_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln680_2_fu_507_p1;
wire   [63:0] zext_ln680_1_fu_566_p1;
reg   [31:0] i_fu_112;
wire   [31:0] i_5_fu_368_p2;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_i_4;
reg   [15:0] empty_fu_116;
wire   [15:0] add_ln651_fu_441_p2;
wire   [15:0] zext_ln680_3_fu_503_p1;
reg   [7:0] empty_40_fu_120;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_idle_pp0_0to0;
reg   [31:0] outValue_fu_124;
wire   [31:0] outValue_2_fu_556_p4;
reg   [31:0] new_match_len_fu_128;
wire   [31:0] new_match_len_3_fu_536_p2;
reg   [0:0] new_matchFlag_1_0_0_07_fu_132;
wire   [0:0] use_boost_fu_479_p2;
reg   [31:0] new_match_loc_fu_136;
wire   [31:0] new_match_loc_5_fu_460_p2;
wire   [31:0] new_match_loc_4_fu_542_p2;
reg    ap_predicate_op104_write_state5;
reg    ap_block_state5_pp0_stage1_iter1_grp2;
reg    ap_block_pp0_stage1_01001_grp2;
reg    ap_block_pp0_stage1_11001_grp2;
wire    ap_block_pp0_stage0_01001;
reg    local_mem_we1_local;
reg    local_mem_ce1_local;
reg    local_mem_ce0_local;
reg   [13:0] local_mem_address0_local;
wire   [1:0] tmp_fu_352_p4;
wire   [13:0] trunc_ln624_1_fu_373_p1;
wire   [0:0] icmp_ln642_1_fu_424_p2;
wire   [0:0] icmp_ln642_fu_418_p2;
wire   [0:0] and_ln642_fu_429_p2;
wire   [13:0] trunc_ln624_fu_408_p1;
wire   [31:0] zext_ln658_fu_457_p1;
wire   [0:0] has_tLen_fu_474_p2;
wire   [0:0] xor_ln668_fu_484_p2;
wire   [7:0] add_ln668_fu_490_p2;
wire   [7:0] select_ln668_fu_495_p3;
wire   [13:0] trunc_ln646_1_fu_465_p1;
wire   [7:0] trunc_ln655_fu_552_p1;
wire   [13:0] trunc_ln646_fu_548_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
reg    ap_done_pending_pp0;
reg    ap_block_pp0;
reg    ap_enable_operation_46;
reg    ap_enable_state3_pp0_iter0_stage2;
reg    ap_predicate_op66_load_state4;
reg    ap_enable_operation_66;
reg    ap_enable_state4_pp0_iter1_stage0;
reg    ap_predicate_op100_load_state5;
reg    ap_enable_operation_100;
reg    ap_enable_state5_pp0_iter1_stage1;
reg    ap_predicate_op81_load_state4;
reg    ap_enable_operation_81;
reg    ap_predicate_op102_load_state5;
reg    ap_enable_operation_102;
reg    ap_predicate_op94_load_state4;
reg    ap_enable_operation_94;
reg    ap_predicate_op106_load_state5;
reg    ap_enable_operation_106;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_582;
reg    ap_condition_586;
reg    ap_condition_590;
reg    ap_condition_291;
reg    ap_condition_599;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp1_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp2_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 i_fu_112 = 32'd0;
#0 empty_fu_116 = 16'd0;
#0 empty_40_fu_120 = 8'd0;
#0 outValue_fu_124 = 32'd0;
#0 new_match_len_fu_128 = 32'd0;
#0 new_matchFlag_1_0_0_07_fu_132 = 1'd0;
#0 new_match_loc_fu_136 = 32'd0;
#0 ap_done_reg = 1'b0;
end

lz4CompressEngineRun_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp1)) begin
                ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp2_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp2_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp2)) begin
                ap_block_pp0_stage1_subdone_grp2_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage0)))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (outFlag_reg_722 == 1'd1) & (match_condition_reg_713 == 1'd0) & (skip_condition_reg_709 == 1'd1) & (icmp_ln624_reg_673_pp0_iter1_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (match_condition_reg_713 == 1'd1) & (skip_condition_reg_709 == 1'd1) & (icmp_ln624_reg_673_pp0_iter1_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (skip_condition_reg_709 == 1'd0) & (icmp_ln624_reg_673_pp0_iter1_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (outFlag_reg_722 
    == 1'd0) & (match_condition_reg_713 == 1'd0) & (skip_condition_reg_709 == 1'd1) & (icmp_ln624_reg_673_pp0_iter1_reg == 1'd0)))) begin
        ap_phi_reg_pp0_iter1_empty_41_reg_272 <= local_mem_q0;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_phi_reg_pp0_iter1_empty_41_reg_272 <= ap_phi_reg_pp0_iter0_empty_41_reg_272;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_40_fu_120 <= nextMatchCh_loc_0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln624_reg_673_pp0_iter1_reg == 1'd0))) begin
        empty_40_fu_120 <= ap_phi_reg_pp0_iter1_empty_41_reg_272;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_fu_116 <= skip_len_reg_load;
        end else if ((1'b1 == ap_condition_590)) begin
            empty_fu_116 <= 16'd0;
        end else if ((1'b1 == ap_condition_586)) begin
            empty_fu_116 <= zext_ln680_3_fu_503_p1;
        end else if ((1'b1 == ap_condition_582)) begin
            empty_fu_116 <= add_ln651_fu_441_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_fu_112 <= 32'd0;
    end else if (((icmp_ln624_reg_673 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        i_fu_112 <= i_5_fu_368_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            new_matchFlag_1_0_0_07_fu_132 <= matchFlag_reg_load;
        end else if ((1'b1 == ap_condition_590)) begin
            new_matchFlag_1_0_0_07_fu_132 <= 1'd1;
        end else if ((1'b1 == ap_condition_586)) begin
            new_matchFlag_1_0_0_07_fu_132 <= use_boost_fu_479_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            new_match_len_fu_128 <= match_len_reg_load;
        end else if ((1'b1 == ap_condition_590)) begin
            new_match_len_fu_128 <= new_match_len_3_fu_536_p2;
        end else if ((1'b1 == ap_condition_586)) begin
            new_match_len_fu_128 <= 32'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            new_match_loc_fu_136 <= match_loc_reg_load;
        end else if ((1'b1 == ap_condition_590)) begin
            new_match_loc_fu_136 <= new_match_loc_4_fu_542_p2;
        end else if ((1'b1 == ap_condition_586)) begin
            new_match_loc_fu_136 <= new_match_loc_5_fu_460_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_599)) begin
        if ((match_condition_fu_435_p2 == 1'd1)) begin
            outValue_fu_124 <= outValue_2_fu_556_p4;
        end else if ((match_condition_fu_435_p2 == 1'd0)) begin
            outValue_fu_124 <= outValue_3_reg_677;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        boostFlag_reg_699 <= boostFlag_fu_362_p2;
        outValue_3_reg_677 <= bestMatchStream_dout;
        tCh_reg_682 <= tCh_fu_332_p1;
        tLen_reg_688 <= {{bestMatchStream_dout[15:8]}};
        tOffset_reg_694 <= {{bestMatchStream_dout[31:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_4_reg_665 <= ap_sig_allocacmp_i_4;
        icmp_ln624_reg_673 <= icmp_ln624_fu_326_p2;
        icmp_ln624_reg_673_pp0_iter1_reg <= icmp_ln624_reg_673;
        match_condition_reg_713 <= match_condition_fu_435_p2;
        outFlag_reg_722 <= outFlag_fu_469_p2;
        skip_condition_reg_709 <= skip_condition_fu_412_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        outValue_1_reg_704 <= outValue_fu_124;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_673 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_673 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (~((ap_loop_exit_ready == 1'b0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0))) begin
        ap_done_pending_pp0 = 1'b1;
    end else begin
        ap_done_pending_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_4 = 32'd0;
    end else begin
        ap_sig_allocacmp_i_4 = i_fu_112;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_673 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        bestMatchStream_blk_n = bestMatchStream_empty_n;
    end else begin
        bestMatchStream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_673 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        bestMatchStream_read = 1'b1;
    end else begin
        bestMatchStream_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage1_grp2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (outFlag_reg_722 == 1'd0) & (match_condition_reg_713 == 1'd0) & (skip_condition_reg_709 == 1'd1) & (icmp_ln624_reg_673_pp0_iter1_reg == 1'd0))) begin
        boosterStream_blk_n = boosterStream_full_n;
    end else begin
        boosterStream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001_grp2) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (ap_predicate_op104_write_state5 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        boosterStream_write = 1'b1;
    end else begin
        boosterStream_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_291)) begin
        if (((match_condition_fu_435_p2 == 1'd1) & (skip_condition_fu_412_p2 == 1'd1))) begin
            local_mem_address0_local = zext_ln680_1_fu_566_p1;
        end else if (((match_condition_fu_435_p2 == 1'd0) & (skip_condition_fu_412_p2 == 1'd1))) begin
            local_mem_address0_local = zext_ln680_2_fu_507_p1;
        end else if ((skip_condition_fu_412_p2 == 1'd0)) begin
            local_mem_address0_local = zext_ln680_fu_447_p1;
        end else begin
            local_mem_address0_local = 'bx;
        end
    end else begin
        local_mem_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln624_reg_673 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (match_condition_fu_435_p2 == 1'd1) & (skip_condition_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln624_reg_673 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (match_condition_fu_435_p2 == 1'd0) & (skip_condition_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln624_reg_673 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (skip_condition_fu_412_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        local_mem_ce0_local = 1'b1;
    end else begin
        local_mem_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        local_mem_ce1_local = 1'b1;
    end else begin
        local_mem_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_673 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        local_mem_we1_local = 1'b1;
    end else begin
        local_mem_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_673 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        new_matchFlag_1_0_0_07_out_ap_vld = 1'b1;
    end else begin
        new_matchFlag_1_0_0_07_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_673 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        new_match_len_out_ap_vld = 1'b1;
    end else begin
        new_match_len_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_673 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        new_match_loc_out_ap_vld = 1'b1;
    end else begin
        new_match_loc_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_673 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        outValue_out_ap_vld = 1'b1;
    end else begin
        outValue_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_673 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out1_ap_vld = 1'b1;
    end else begin
        p_out1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln624_reg_673 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_done_pending_pp0 == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln651_fu_441_p2 = ($signed(empty_fu_116) + $signed(16'd65535));

assign add_ln668_fu_490_p2 = ($signed(tLen_reg_688) + $signed(8'd255));

assign and_ln642_fu_429_p2 = (icmp_ln642_fu_418_p2 & icmp_ln642_1_fu_424_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_pp0 = (((ap_ST_fsm_pp0_stage1 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage1_subdone)) | ((ap_ST_fsm_pp0_stage2 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage2_subdone)) | ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone)));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001_grp2 = ((1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage1_iter1_grp2));
end

assign ap_block_pp0_stage1_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp1 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp2 = ((1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage1_iter1_grp2));
end

assign ap_block_pp0_stage1_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1)) | ((1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage1_iter1_grp2)));
end

assign ap_block_pp0_stage1_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp1 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp2 = ((1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage1_iter1_grp2));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0_grp1 = ((bestMatchStream_empty_n == 1'b0) & (icmp_ln624_reg_673 == 1'd0));
end

always @ (*) begin
    ap_block_state5_pp0_stage1_iter1_grp2 = ((boosterStream_full_n == 1'b0) & (ap_predicate_op104_write_state5 == 1'b1));
end

always @ (*) begin
    ap_condition_291 = ((icmp_ln624_reg_673 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_582 = ((icmp_ln624_reg_673 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (skip_condition_fu_412_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_586 = ((icmp_ln624_reg_673 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (match_condition_fu_435_p2 == 1'd0) & (skip_condition_fu_412_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_590 = ((icmp_ln624_reg_673 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (match_condition_fu_435_p2 == 1'd1) & (skip_condition_fu_412_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_599 = ((icmp_ln624_reg_673 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (skip_condition_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

always @ (*) begin
    ap_enable_operation_100 = (ap_predicate_op100_load_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_102 = (ap_predicate_op102_load_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_106 = (ap_predicate_op106_load_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_46 = (icmp_ln624_reg_673 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_66 = (ap_predicate_op66_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_81 = (ap_predicate_op81_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_94 = (ap_predicate_op94_load_state4 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_enable_state3_pp0_iter0_stage2 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2));
end

always @ (*) begin
    ap_enable_state4_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state5_pp0_iter1_stage1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign ap_phi_reg_pp0_iter0_empty_41_reg_272 = 'bx;

always @ (*) begin
    ap_predicate_op100_load_state5 = ((skip_condition_reg_709 == 1'd0) & (icmp_ln624_reg_673_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op102_load_state5 = ((match_condition_reg_713 == 1'd0) & (skip_condition_reg_709 == 1'd1) & (icmp_ln624_reg_673_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op104_write_state5 = ((outFlag_reg_722 == 1'd0) & (match_condition_reg_713 == 1'd0) & (skip_condition_reg_709 == 1'd1) & (icmp_ln624_reg_673_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op106_load_state5 = ((match_condition_reg_713 == 1'd1) & (skip_condition_reg_709 == 1'd1) & (icmp_ln624_reg_673_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op66_load_state4 = ((icmp_ln624_reg_673 == 1'd0) & (skip_condition_fu_412_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op81_load_state4 = ((icmp_ln624_reg_673 == 1'd0) & (match_condition_fu_435_p2 == 1'd0) & (skip_condition_fu_412_p2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op94_load_state4 = ((icmp_ln624_reg_673 == 1'd0) & (match_condition_fu_435_p2 == 1'd1) & (skip_condition_fu_412_p2 == 1'd1));
end

assign ap_ready = ap_ready_sig;

assign boostFlag_fu_362_p2 = ((tmp_fu_352_p4 == 2'd0) ? 1'b1 : 1'b0);

assign boosterStream_din = outValue_1_reg_704;

assign has_tLen_fu_474_p2 = ((tLen_reg_688 != 8'd0) ? 1'b1 : 1'b0);

assign i_5_fu_368_p2 = (i_4_reg_665 + 32'd1);

assign icmp_ln624_fu_326_p2 = ((ap_sig_allocacmp_i_4 == sub) ? 1'b1 : 1'b0);

assign icmp_ln642_1_fu_424_p2 = ((tCh_reg_682 == empty_40_fu_120) ? 1'b1 : 1'b0);

assign icmp_ln642_fu_418_p2 = ((new_match_len_fu_128 < 32'd255) ? 1'b1 : 1'b0);

assign local_mem_address0 = local_mem_address0_local;

assign local_mem_address1 = zext_ln634_fu_376_p1;

assign local_mem_ce0 = local_mem_ce0_local;

assign local_mem_ce1 = local_mem_ce1_local;

assign local_mem_d1 = tCh_reg_682;

assign local_mem_we1 = local_mem_we1_local;

assign match_condition_fu_435_p2 = (new_matchFlag_1_0_0_07_fu_132 & and_ln642_fu_429_p2);

assign new_matchFlag_1_0_0_07_out = new_matchFlag_1_0_0_07_fu_132;

assign new_match_len_3_fu_536_p2 = (new_match_len_fu_128 + 32'd1);

assign new_match_len_out = new_match_len_fu_128;

assign new_match_loc_4_fu_542_p2 = (new_match_loc_fu_136 + 32'd1);

assign new_match_loc_5_fu_460_p2 = (i_4_reg_665 - zext_ln658_fu_457_p1);

assign new_match_loc_out = new_match_loc_fu_136;

assign outFlag_fu_469_p2 = ((i_4_reg_665 == 32'd0) ? 1'b1 : 1'b0);

assign outValue_2_fu_556_p4 = {{outValue_fu_124[31:16]}, {trunc_ln655_fu_552_p1}, {outValue_fu_124[7:0]}};

assign outValue_out = outValue_fu_124;

assign p_out = empty_40_fu_120;

assign p_out1 = empty_fu_116;

assign select_ln668_fu_495_p3 = ((xor_ln668_fu_484_p2[0:0] == 1'b1) ? add_ln668_fu_490_p2 : 8'd0);

assign skip_condition_fu_412_p2 = ((empty_fu_116 == 16'd0) ? 1'b1 : 1'b0);

assign tCh_fu_332_p1 = bestMatchStream_dout[7:0];

assign tmp_fu_352_p4 = {{bestMatchStream_dout[31:30]}};

assign trunc_ln624_1_fu_373_p1 = i_4_reg_665[13:0];

assign trunc_ln624_fu_408_p1 = new_match_loc_fu_136[13:0];

assign trunc_ln646_1_fu_465_p1 = new_match_loc_5_fu_460_p2[13:0];

assign trunc_ln646_fu_548_p1 = new_match_loc_4_fu_542_p2[13:0];

assign trunc_ln655_fu_552_p1 = new_match_len_3_fu_536_p2[7:0];

assign use_boost_fu_479_p2 = (has_tLen_fu_474_p2 & boostFlag_reg_699);

assign xor_ln668_fu_484_p2 = (use_boost_fu_479_p2 ^ has_tLen_fu_474_p2);

assign zext_ln634_fu_376_p1 = trunc_ln624_1_fu_373_p1;

assign zext_ln658_fu_457_p1 = tOffset_reg_694;

assign zext_ln680_1_fu_566_p1 = trunc_ln646_fu_548_p1;

assign zext_ln680_2_fu_507_p1 = trunc_ln646_1_fu_465_p1;

assign zext_ln680_3_fu_503_p1 = select_ln668_fu_495_p3;

assign zext_ln680_fu_447_p1 = trunc_ln624_fu_408_p1;

endmodule //lz4CompressEngineRun_lzBooster_255_16384_64_Pipeline_lz_booster
